spring.application.name=reserva-service
server.port=8083

# DataSource configuration mapped from environment
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Feign configuration
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# Feign Client URLs
auth.service.url=${AUTH_SERVICE_URL:http://auth-service:8081}
notificacion.service.url=${NOTIFICACION_SERVICE_URL:http://notificacion-service:8085}
evento.service.url=${EVENTO_SERVICE_URL:http://evento-service:8082}
