server:
  port: 8086

spring:
  application:
    name: admin-service

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

logging:
  level:
    org.springframework.web: INFO
    com.evently: DEBUG

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}
pago:
  service:
    url: ${PAGO_SERVICE_URL:http://pago-service:8084}
evento:
  service:
    url: ${EVENTO_SERVICE_URL:http://evento-service:8082}
